repos:
  - repo: https://github.com/MagmaMoose/chargate
    rev: v1
    hooks:
      - id: shellcheck
      - id: actionlint
      - id: hadolint
      - id: trivy
      - id: trufflehog
      - id: semgrep
      - id: checkov
